osisoft/OCS-Docs

- Documentation/DataIngress/OMF_Ingress_Publishers.md
- Documentation/DataIngress/OMF_Ingress_Topics.md
Due to code cleanups and an ongoing effort to adhere to better adhere to REST API guidelines, Parse has removed the following routes:
- POST api/tenants/{tenantId}/publishers
- DELETE api/tenants/{tenantId}/publishers/{publisherId}/tokens
- POST api/tenants/{tenantId}/namespaces/{namespaceId}/topics
- POST api/tenants/{tenantId}/namespaces/{namespaceId}/publishertopicmapping
- POST api/tenants/{tenantId}/namespaces/{namespaceId}/publishertopicmappings
- DELETE api/tenants/{tenantId}/namespaces/{namespaceId}/publishertopicmappings/{topicId}
> Update Parse Docs

- _exported_templates/default/styles/docfx.js
Changed the minimum query length from 3 characters to 2 after receiving user feedback that relevant search terms, such as PI and QI, were being ignored.
> Lowered the minimum query length to 2 characters.

- Documentation/DataIngress/OMF_Ingress_Specification.md
- Documentation/DataIngress/toc.yml
- Documentation/SequentialDataStore/Filter_Expressions.md
- index.md
I removed the Quick Start section in OMF Ingress. It only pointed to the quick start section for SDS and caused errors when selecting that link in the page.
Other changes were just minor clean up:
- Changed supported OMF version to 1.1
- Fixed a couple of references to QiTypeCode
> Update OMF Ingress page

- Documentation/SequentialDataStore/SDS_Types.md
Get Reference Count now returns a dictionary rather than a single int.
> Update Get Reference Count

- Documentation/SequentialDataStore/Searching.md
Quotes are not ASCII quotes, making copy-pasting examples into source code not compile.
> Update Searching.md - fixing "smart" quotes

- Documentation/SequentialDataStore/SDS_Streams.md
- Documentation/SequentialDataStore/SDS_Types.md
- Documentation/SequentialDataStore/SDS_Views.md
- Documentation/SequentialDataStore/Units_of_Measure.md
Fixed the access control links in the documentation for Types, Streams, Stream Views, and Units of Measure
> Fixed access control links

- Documentation/samples.md
OSI-Samples was restructured. Updating the links in ocs-docs to reflect the restructuring.
> Update the links to OCS Samples

- _exported_templates/default/styles/docfx.css
To make some previously hidden content visible, this CSS change sets a reasonable maximum width for the side affixed content and allows it to wrap if content is too long.
> Correcting cut off content in sidebar

- Documentation/OSIsoft_Cloud_Services.md
Remove redundant descriptions of components and ordered the components to match the navigation.
Fixes #154
> Removed redundant text

- Documentation/SequentialDataStore/Units_of_Measure.md
I.e. means "in other words", usually if you want to tell someone a more commonly used synonym to a word that they may not be familiar with.  E.g. means "for example", which seems more appropriate in the context of how "i.e." is being used here.  Meter is not a synonym for "unit of measure", it's an example of a unit.
Fixes #155
> Changing i.e. to e.g.

- Documentation/SequentialDataStore/Units_of_Measure.md
The use of exempli gratia (e.g.) is accurate but a plain English may be easier for a broader audience.
> Spelling out e.g. to "for example"

- Documentation/SequentialDataStore/Reading_Data_API.md
I added explanations on which summary calculations are event weighted vs index weighted, as well as fixing the summary counts and adding the new index count to the summary.
> Fixed summary count and explained calculations

- Documentation/SequentialDataStore/SdsStreamExtra.md
This is an update for the stream metadata API that includes the method to support patch updates to metadata. This API is still being reviewed, so we can keep this PR open until the API changes are actually rolled out.
> Update stream metadata for patch method

- Documentation/SequentialDataStore/SDS_Types.md
Per WI 29352, removing internal types in customer-facing documentation.
> Removing SDSxxx types

- _exported_templates/default/partials/footer.tmpl.partial
so that it automatically updates with the latest year that the documentation was updated.
> Changed 2020 in the footer to $COPYRIGHT_YEAR

- Documentation/Metadata/Metadata_Rules_Overview.md
This was done as part of push to GA. As requested by Product Management since the feature is moving into general availability it should no longer be marked as preview in the documentation.
> Removed (Preview) from documentation

- Documentation/samples.md
Updating links to java, python, and nodeJs as examples are not working on the samples page.
> Updating links to the code samples

- Content_Portal/Documentation/DataViews/Data_API.md
- Content_Portal/Documentation/DataViews/Getting_Data.md
- Content_Portal/Documentation/DataViews/Preview_Data_API.md
We now calculate default page size instead of hard-coding it as 1,000.
The PR reflects this changes in the description of the query parameter "count" for both preview and non-preview GetData endpoints.
> Change description of the "count" query param in GetData

- Content_Portal/Documentation/SequentialDataStore/SDS_Streams.md
- Content_Portal/Documentation/SequentialDataStore/indexes.md
Adding a line as part of the WI 136155.
If the primary index is a compound index, secondary indexes will only be valid if the compound index has a maximum of 2 properties.
> Adding a line on how compound indexing of the primary index affects secondary indexes

- _exported_templates/default/styles/docfx.vendor.css
Hi, I made a minor change to the font that governs the color for code. 
An example of this is in the Asset API topic (Laureen, don't worry, I'm only pushing this one CSS file and not anything related to Assets).  Check out the Get Asset ID H2 heading in both production and CLGUILD to see the difference. 
We used to use a reddish font color and that is currently being used for OCS in production. I've changed the color to the dark grey that we've adopted for Edge/Adapter docs.
> updated code font

- Content_Portal/Documentation/SequentialDataStore/SDS_Streams.md
- Content_Portal/Documentation/SequentialDataStore/SDS_Types.md
- Content_Portal/Documentation/SequentialDataStore/SDS_Views.md
- Content_Portal/Documentation/SequentialDataStore/Units_of_Measure.md
Fixing inaccurate response description on 404 throughout SDS API documentation. Specifically, it should be resource, not data view or query. Missed while reviewing ACL Patch API addition.
> Fixing inaccurate response description on 404

- Content_Portal/Documentation/DataViews/DefineaDataView/Data_Items_and_Groups.md
Update and clarify the documentation on which data item field types are considered eligible.
Primary change: TimeSpan and NullableTimeSpan are now considered ineligible.
> Update field type eligibility

- Content_Portal/Documentation/SequentialDataStore/SDS_Types.md
1. Remove SDS prefixes where deemed extraneous
2. Correct overcapitalization
> Updating the types topic according to Architecture standard

- Content_Portal/Overview/what-does-ocs-do.md
- Content_Portal/set-up/clients-concept.md
- Content_Portal/set-up/roles-concept.md
Incorporating any content in the existing concept topics that doesn't appear in the Reorg TOC branch.
I examined the content found in the 3 existing concept topics (introduction-to-data-storage.md, introduction-to-preconfigured-roles, introduction-to-account-management) for information that doesn't exist in the lasato-ocs_docs_reorg branch topics. I added the information into suitable topics within the lasato-ocs_docs_reorg branch.
The reason is that the 3 existing concept topics are going away and we want to preserve relevant information to the customer.
> Incorporating existing concept topics

- Content_Portal/set-up/roles-concept.md
- Content_Portal/set-up/roles-procedure.md
Hi Doug and Derek,
One of the OCS writers raised a question about how we talk about roles being the mechanism by which users' permissions to OCS resources is determined. The question is whether we should be clearer that it is a combination of roles and ACLs that determine whether a user has access to a resource or not.
Please take a look at Josh's comments and see what you think. Thanks
> Added Josh's feedback about ACLs and roles

- Content_Portal/Documentation/Asset Rules/asset-rules.md
Since this change was made to the Assets API and the backend of the rules API, the documentation needs to be updated to reflect the current state.
> Rename References to StreamReferences

- Content_Portal/Documentation/Management/Account_Tenant.md
Account_Tenant.md has a broken link as well as some improper wording:
Tenants
APIs to manage an OCS Customer tenant account. A tenant represents the set of services, applications, data, and configuration state available to a customer. Users are associated with a tenant via at least one configured identity provider and access to resources can be managed for those users via the assignment of roles. Data and services provided by a tenant may also span geographical regions. A tenant has APIs to manage an OCS customer tenant. Unlike namespaces, tenants are not scoped to a region. Tenant level information, such as users and clients, is stored in all supported regions for read-only purposes. **Write operations for tenant management and identity and access management are only supported through …
> fix broken link in tenant per Chris M.

- content/api-reference/identity/toc.yml
DocuPipe is now updated to match the file name with the h1 header. But the title in the toc still has the old name. Updating the toc once to make sure that they're in line.
> Match file name with the toc title

- content/external-references/parameters.yaml
Added the qualilfication "OCS" to tenantId description because we deal with an Azure Active Directory tenant.
Added a new key for query for Azure Active Directory
> Added "OCS" to "tenant identifier; added an aadQuery key

- content/api-reference/identity/identity-claims.md
- content/api-reference/identity/identity-client-credential-clients-roles.md
- content/api-reference/identity/identity-client-credential-clients.md
- content/api-reference/identity/identity-hybrid-clients.md
- content/api-reference/identity/identity-identity-providers.md
- content/api-reference/identity/identity-invitations.md
- content/api-reference/identity/identity-tenants-roles.md
- content/api-reference/identity/identity-tenants-users.md
- content/api-reference/identity/identity-users-roles.md
Removed the "TODO: Remove the internal model" sentence from 9 API markdown files.
I will address this in the codebase shortly, but this is to fix in the immediate term on ZoomIn
> Removed the erroneous internal "TODO: Remove the internal model" comments from 9 API markdown topics

- content/external-references/common.yaml
- content/external-references/dataviews-headers.yaml
- content/external-references/dataviews-parameters.yaml
- content/external-references/dataviews-response-codes.yaml
- content/external-references/dataviews-summaries.yaml
- content/external-references/parameters.yaml
- content/external-references/responses.yaml
- content/external-references/sds.yaml
Per our discussions and agreements, I am adding a period (.) at the end of all parameter descriptions and response code descriptions in :
-common.yml
-parameters.yml
-responses.yml
In addition, I examined other yaml files in our \external-references repo for description sentences without a period, and added a period to them.
> Adding periods (.) to all external references

- content/external-references/dataviews-parameters.yaml
This PR contributes documentation for a parameter of the Data Views API: `cache`, in the context of the `/preview/dataviews/data/*` routes.
Note that this new external reference (`cache-data-preview`) is an adaptation of an existing external reference (`cache-data`). Both will be used going forward.
> Add cache-data-preview parameter to data views external references

- content/add-organize-data/store-data/types/types-concept.md
It appears that the subheadings in "Create and configure an asset" and "Create an asset type with the asset types editor" already appear in the In This Topic links. Therefore, I did not make any changes to these topics.
> Edits for consistency

- content/external-references/common.yaml
- content/external-references/dataviews-parameters.yaml
- content/external-references/dataviews-summaries.yaml
Data Views uses ext refs that reference back to the older ocs-docs URLs. I replaced them with the corresponding xref to the files.
> updated older ocs-docs links with xrefs

- content/developer-guide/sequential-data-store-dev/sds-quick-start.md
File relocated as a result of restructuring.  Adding a note for after the program release.
@digitaljoshua
> Adding a note on timeout header (Do not merge until Kane says so)

- content/api-reference/community/community-shared-access.md
Proposing URL updates which missed "tenants" before tenantId
> Proposing URL updates which missed "tenants" before tenantId

- content/api-reference/identity/toc.yml
- content/api-reference/toc.yml
* Moved "Role-based access control" from **API Reference > Role-based access control** to **API Reference > Identity and access management > Role-based access control**. 
*  Corrected a title typo.
[output preview](https://osisoft-dev.zoominsoftware.io/bundle/ocs-docupipe-identity-toc-update/page/developer-guide/identity-dev/dev-guide-role-based-access-control_1.html)
> Identity TOC Reorg

- content/api-reference/assets/toc.yml
- content/api-reference/toc.yml
* Alphabetized TOC for API Reference > Asset store.
* Retitled "Asset and AssetType ACL" to "Access control".
* Retitled "Asset and asset type status" to "Assets status"
* Fixed a couple typos.
[Output preview](https://osisoft-dev.zoominsoftware.io/bundle/ocs-docupipe-assets-toc-update/page/api-reference/assets/assets-access-control-list.html)
> Asset Store TOC reorg

- content/api-reference/toc.yml
* Alphabetized **API Reference** TOC.
* Removed **Role-based access control**, which moved to **Identity and access management** in a separate PR.
This PR is dependent on the remaining TOC PRs. Those must be merged first.
[output preview](https://osisoft-dev.zoominsoftware.io/bundle/ocs-api-reference-toc-update/page/api-reference/ocs-api-reference.html)
> API Reference root TOC reorg

- content/developer-guide/data-views-dev/get-data-view-data/quick-start-get-data-view-data.md
Added response format section for accept-verbosity header for data views, see the change in the Response format section in our documentation dev environment here: https://osisoft-dev.zoominsoftware.io/bundle/ocs-rmuolic-pbi-276832-data-views-accept-verbosity-header/page/developer-guide/data-views-dev/get-data-view-data/quick-start-get-data-view-data.html#format
> added response format section

- content/add-organize-data/collect-data/connectors/pi-to-ocs/main-lp.md
Small addition to the main landing page for PI to OCS. Added first sentence in response to customer feedback/confusion about why "Preview" still appears in the TOC menu. Will also add this to the ADH version of the doc. Ironically, "Preview" will be removed in a few sprints.
> Vtouati pbi 273735 preview status

- content/developer-guide/omf-dev/omf-sds-vs-omf.md
- content/developer-guide/toc.yml
Hi Collin,
Good draft! Here are the tweaks I made to your article. 
- Replaced upfront links with a comparison table for TLDR people. 
- Minor spelling and grammar changes.
- Added a couple of headings for doc structure that our portal uses to make a mini toc.
- Replaced a few link URLs with IDs for more resiliency.
- Replaced AVEVA branding with OSIsoft. We're in state where we're maintaining two doc sets--one for OCS and one for ADH. We're merging into the OCS doc set here. When I merge these changes downstream to ADH, I'll do the rebrand then. 
- I also added this doc to the OCS toc. There's a preview available [here](https://osisoft-dev.zoominsoftware.io/bundle/ocs-mbishop-edits-sds-vs-omf/page/developer-guide/omf-dev/omf-sds-vs-omf.html).
> Mbishop edits sds vs omf

- content/developer-guide/sequential-data-store-dev/sds-read-data.md
Behavior of the maximum read count setting has changed from setting a constraint on the number of events returned during a read data call, to the number of events accessed.
> Update description of event limit for read calls

- content/overview/search.md
Hi @RealVictorZhang ,
I made the changes that we discussed during our call yesterday. I made the following changes:
- Updated the title. The title change jumps this topic to the top of the search results for "search". You can confirm them [here](https://osisoft-dev.zoominsoftware.io/bundle/ocs-366220-merge-two-search-topics/page/ocs-content-portal-overview.html).
- Updated the existing example to accurately describe a tokenized search for "Id:X* AND Metadata/Name:B*"
- Added a new example for "Id:X* AND Metadata/Name:"B"*", which will give the user who raised the ticket the result they were expecting.
- Added the search example from "SDS Search" in the developer documentation.
> 366220 correct incorrect information in search documentation and add more examples
