Documentation/SequentialDataStore/SDS_Views.md
Documentation/SequentialDataStore/toc.yml

Updated name of views to be more specific.

Updated "Views" to "Stream Views"

---

index.md

Updated the index by changing  Sds View to Stream View to reflect the name changed of the section.

Updated index with Stream View

---

Documentation/SequentialDataStore/SDS_Views.md

Removing old link to read the docs.

remove link to readthedocs

---

Documentation/Management/Consent.md
Documentation/Management/toc.yml
index.md

Add documentation for consent workflow

Added consent instructions

---

Documentation/SequentialDataStore/Quick_Start.md
Documentation/SequentialDataStore/Reading_Data.md
Documentation/SequentialDataStore/Reading_Data_API.md
Documentation/SequentialDataStore/SDS_Streams.md
Documentation/SequentialDataStore/SDS_Types.md
Documentation/SequentialDataStore/SDS_Views.md
Documentation/SequentialDataStore/SdsStreamExtra.md
Documentation/SequentialDataStore/Searching.md
Documentation/SequentialDataStore/Units_of_Measure.md
Documentation/SequentialDataStore/Writing_Data.md
Documentation/SequentialDataStore/Writing_Data_API.md
Documentation/SequentialDataStore/table_format.md

Added versioning (v1-preview) to all routes in the SDS documentation

Added API versioning to all Sds routes

---

Documentation/SequentialDataStore/Compression.md
Documentation/SequentialDataStore/SDS_Streams.md
Documentation/SequentialDataStore/indexes.md

Fixed the formatting of the parameters in SDS_Streams.md

Fixed formatting of parameters

---

Documentation/Management/Account_ClientRole.md
Documentation/Management/Account_Namespace.md
Documentation/Management/Account_NamespaceTier.md
Documentation/Management/Account_Role.md
Documentation/Management/Account_RootAccessControl.md
Documentation/Management/Account_ServiceBlog.md
Documentation/Management/Account_Tenant.md
Documentation/Management/Account_TenantFeatureState.md
Documentation/Management/Account_UserRole.md
Documentation/Management/Management_Overview.md

- Routes in the API docs were updated to include API version information.
- Documentation was also added for Tenant Icons.

API Versioning Doc Update

---

Documentation/SequentialDataStore/Filter_Expressions.md
Documentation/SequentialDataStore/Reading_Data.md
Documentation/SequentialDataStore/Reading_Data_API.md
Documentation/SequentialDataStore/SDS_Types.md

Fixed spacing, links, and typos

Fixed minor bugs

---

Documentation/SequentialDataStore/Reading_Data.md

Replaced Multi-stream header with Bulk to mirror the route

Replaced Multi-stream with Bulk to mirror the route

---

Documentation/Management/Account_ClientRole.md
Documentation/Management/Account_Namespace.md
Documentation/Management/Account_NamespaceTier.md
Documentation/Management/Account_Role.md
Documentation/Management/Account_RootAccessControl.md
Documentation/Management/Account_ServiceBlog.md
Documentation/Management/Account_Tenant.md
Documentation/Management/Account_TenantFeatureState.md
Documentation/Management/Account_UserRole.md

Updated account management docs to new standards.

Update to new standards

---

Documentation/SequentialDataStore/SdsStreamExtra.md

Should be Delete Tags instead of Delete Metadata

metadata -> tags

---

Documentation/SequentialDataStore/SDS_Streams.md
Documentation/SequentialDataStore/SDS_Types.md
Documentation/SequentialDataStore/SDS_Views.md

Updated Streams, Types, and Stream Views documentation to reflect the new character restrictions.

Id Restrictions

---

Documentation/Identity/Identity_Client.md
Documentation/Identity/Identity_ClientCredentialClient.md
Documentation/Identity/Identity_HybridClient.md
Documentation/Identity/Identity_IdentityProvider.md
Documentation/Identity/Identity_ImplicitClient.md
Documentation/Identity/Identity_Invitation.md
Documentation/Identity/Identity_Secret.md
Documentation/Identity/Identity_User.md

- Fix singular model names in uris @osimarkrogers

Fix singular model names in uris

---

Documentation/Identity/Identity_Secret.md

s missing from Secrets in request: POST api/v1-preview/Tenants/{tenantId}/ClientCredentialClients/{clientId}/Secret/

missing character in API call

---

Documentation/SequentialDataStore/Compression.md
Documentation/SequentialDataStore/Introducing_SDS.md
Documentation/SequentialDataStore/SDS_Streams.md
Documentation/SequentialDataStore/SDS_Types.md
Documentation/SequentialDataStore/SDS_Views.md

Changed the SDS Preview to the OCS preview and fixed a few typos.

Typos and Formatting

---

Documentation/Management/Account_Namespace.md
Documentation/Management/Account_Role.md
Documentation/Management/Account_ServiceBlog.md
Documentation/Management/Account_Tenant.md

- New information for Namespace, Role, & Tenant routes
- Added new route to Service Blog

 April updates to Management API Docs

---

Documentation/SequentialDataStore/Quick_Start.md

* Fixed the OCSClients link
* Removed extra lines under headings
* Changed stream definition to have the full object

Quick start formatting errors

---

index.md

Removed link to Filtering - SDS Objects

---

Documentation/DataIngress/OMF_Ingress_Subscriptions.md
Documentation/DataIngress/OMF_Ingress_Topics.md

For topics and subscriptions, POST is now Create, PUT is Update.

Update OmfIngress route documentation

---

Documentation/SequentialDataStore/Reading_Data.md
Documentation/SequentialDataStore/Reading_Data_API.md

Note:  this includes the GetSampleFiltered methods which are coming soon.

Sampled Values

---

Documentation/OSIsoft_Cloud_Services.md
Documentation/SequentialDataStore/Data_Store_and_SDS.md
Documentation/SequentialDataStore/Reading_Data_API.md
Documentation/support.md

Fixed weird quotes
Updated the sampled values route

Sds Errors

---

Documentation/Identity/Identity_User.md

- Add possible status values to Users/Status
@osimarkrogers

Add invitation statuses

---

Documentation/samples.md

Added links to the OCS and OSI samples to make it easier for customers to follow.

Added links to the samples

---

Documentation/SequentialDataStore/SDS_Types.md

Fixes based on Robert's feedback

Typos in the interpolation changes

---

Documentation/SequentialDataStore/SDS_Streams.md
Documentation/SequentialDataStore/SDS_Types.md
Documentation/SequentialDataStore/SDS_Views.md
Documentation/SequentialDataStore/Units_of_Measure.md

Corrected the access control routes for the collection level acls.

Fixed default ACL routes for Streams, Types, Stream Views, and Quantities

---

Documentation/DataViews/DataRetrieval.md
Documentation/DataViews/DataRetrieval_API.md

This route is no longer supported and is being removed

Remove Get Datagroup by Id route

---

Documentation/SequentialDataStore/SDS_Types.md

For Interpolation Modes:
- ContinuousNullableLeading 
- ContinuousNullableTrailing

Updated extrapolation values

---

Documentation/SequentialDataStore/Searching.md

Added section to Searching.md for trailing punctuation.

Documentation trailing punctuation

---

Documentation/Management/Account_Namespace_1.md
Documentation/Management/Account_Tenant.md
Documentation/OSIsoft_Cloud_Services.md

Updates to OSIsoft_Cloud_Services, Account_Tenant, and Account_Namespace_1 per discussion with Elizabeth McErlean

Osimarkrogers patch 7

---

Documentation/SequentialDataStore/Reading_Data.md
Documentation/SequentialDataStore/Reading_Data_API.md
Documentation/SequentialDataStore/SDS_Streams.md
Documentation/SequentialDataStore/SDS_Types.md

Updating the extrapolation section based on WI 36667 (Update the behavior of Extrapolation Mode to follow Documentation). Moving interpolation and extrapolation sections out of "Types" to "Reading Data"

Update the extrapolation section

---

Documentation/SequentialDataStore/Units_of_Measure.md

Need to ask a question on  `Get Quantity Uom`

Using headers instead of boldface  for API calls

---

Documentation/SequentialDataStore/Quick_Start.md
Documentation/SequentialDataStore/Reading_Data_API.md
Documentation/SequentialDataStore/Units_of_Measure.md
Documentation/SequentialDataStore/Writing_Data_API.md

Playing with headers for request, response, and parameters.

Playing with headers for requests and response

---

_exported_templates/default/partials/footer.tmpl.partial

Update copyright year in docs footer, as requested by Legal.

Bump copyright year

---

Documentation/DataViews/Data_Views_Overview.md

Hi Daphne,
Pls see if you think this additional content meshes with the existing introduction.

Update Data Views Overview

---

Documentation/SequentialDataStore/Quick_Start.md
Documentation/SequentialDataStore/Reading_Data.md
Documentation/SequentialDataStore/Reading_Data_API.md
Documentation/SequentialDataStore/SDS_Streams.md
Documentation/SequentialDataStore/SDS_Types.md
Documentation/SequentialDataStore/SDS_Views.md
Documentation/SequentialDataStore/SdsStreamExtra.md
Documentation/SequentialDataStore/Searching.md
Documentation/SequentialDataStore/Writing_Data.md
Documentation/SequentialDataStore/Writing_Data_API.md

Using consistent terminology around ".NET library". ".NET client libraries method" to be used in its place.

Giselleleeosi api template

---

Documentation/Operations/Operations_Resource Usage Data.md

Added new field in the model for ResourceUsage

New field in model

---

Documentation/SequentialDataStore/Reading_Data.md
Documentation/SequentialDataStore/Writing_Data.md

Associated WI: https://dev.azure.com/osieng/engineering/_workitems/edit/113324

Timestamp handling in SDS

---

Documentation/DataViews/Getting_Data.md

Update documentation with short explanation of data field mapping count limit.

updated field mapping count limit

---

Documentation/Operations/Operations_Health.md
Documentation/Operations/Operations_Metrics.md
Documentation/Operations/toc.yml
index.md

Adding health and metrics APIs

Health and Metrics APIs

---

Documentation/Operations/Operations_Health.md

Model changed for this API and needs to updated. Apologies, this snuck by me.

New model for response type

---

Documentation/SequentialDataStore/SdsStreamExtra.md

Adopted the tags and metadata docs to the new standardized format.

Standardizing format

---

Content_Portal/Concepts/toc.yml

Fixed Concepts\toc.yml file. Changed topichref to topicHref.

Fixed toc.yml file

---

Content_Portal/Documentation/SequentialDataStore/Reading_Data.md

Adding two rows to the interpolation table for object type and empty type

Adding two rows to the interpolation table

---

Content_Portal/Documentation/SequentialDataStore/Reading_Data_API.md

Adding a link to the concept topics on interpolation and extrapolation out of reading data APIs.

[WI 152153] Adding a link to the interpolation and extrapolation sections out of reading data API > Index collection

---

Content_Portal/Documentation/SequentialDataStore/Reading_Data.md
Content_Portal/Documentation/SequentialDataStore/SDS_Views.md

Prepping the content for additional information (overriding auto-mapping and supported mapping)

[WI 150036] Update SDS_Views.md

---

Content_Portal/Documentation/Assets/Asset-Measurements.md
Content_Portal/Documentation/Assets/Assets.md

Review the Asset Measurements and MeasurementsMapping topic (Asset-Measurements.md file).

Review the Assets.md file

---

Content_Portal/Documentation/Assets/Asset-Measurements.md

Please review the entire file.

Review Asset-Measurements.md

---

Content_Portal/Documentation/Assets/Asset-Measurements.md
Content_Portal/Documentation/Assets/Assets.md

Hi Anthony,
I cleaned up "MeasurementsMapping" and changed all occurrences to "Measurement Mappings" and 
"measurements mapping" to "measurement mappings."

Resubmitting PR on Asset-Measurements.md

---

Content_Portal/Documentation/Assets/Asset-Centric-Data-API.md
Content_Portal/Documentation/Assets/Asset-Measurements.md
Content_Portal/Documentation/Assets/Asset-Search-API.md
Content_Portal/Documentation/Assets/Asset-Type.md
Content_Portal/Documentation/Assets/Assets-API.md
Content_Portal/Documentation/Assets/Assets.md

There is more to do once the asset type file and others are checked in

Updates from asset concordance

---

_exported_templates/default/partials/logo.tmpl.partial
_exported_templates/default/partials/navbar.tmpl.partial

updated two partial files to fix OSIsoft logo.

updates to logo

---

Content_Portal/Documentation/Assets/Access-Control-API.md
Content_Portal/Documentation/Assets/Asset-Centric-Data-API.md
Content_Portal/Documentation/Assets/Asset-Measurements.md
Content_Portal/Documentation/Assets/Asset-Search-API.md
Content_Portal/Documentation/Assets/Asset-Type.md
Content_Portal/Documentation/Assets/Assets-API.md
Content_Portal/Documentation/Assets/Assets.md
Content_Portal/Documentation/Assets/asset-default-shape.md
Content_Portal/Documentation/Assets/asset-status-mapping.md
Content_Portal/Documentation/Assets/toc.yml
Content_Portal/Documentation/toc.yml

This PR includes:
- Edits in response to Todd's comments
- Cleaned up terminology: ID -> Id; attribute -> metadata; metadatum -> metadata value
- Other minor editing and formatting
- Removed "Authorization" section from APIs
Please note: There are several questions. 
Thanks!

Minor edits and a few questions

---

Content_Portal/Concepts/Account_Management_Concepts.md
Content_Portal/Concepts/toc.yml
Content_Portal/Documentation/Identity/Identity_Invitation.md
Content_Portal/Documentation/Identity/Identity_User.md
Content_Portal/Documentation/Management/Account_ClientRole_1.md
Content_Portal/Documentation/Management/Account_Namespace_1.md
Content_Portal/Documentation/Management/Account_Role_1.md
Content_Portal/Documentation/Management/Account_RootAccessControl_1.md
Content_Portal/Documentation/Management/Account_Tenant.md
Content_Portal/Documentation/Management/Account_TenantFeatureState.md
Content_Portal/Documentation/Management/Account_UserRole_1.md
Content_Portal/Documentation/Management/Management_Overview.md
Content_Portal/Documentation/OSIsoft_Cloud_Services.md
Content_Portal/Documentation/toc.yml

reverting the specific identified changes from the previous PR #310

Digitaljoshua identity to acctmgmt revert

---

Content_Portal/Documentation/SequentialDataStore/SDS_Streams.md
Content_Portal/Documentation/SequentialDataStore/SDS_Types.md
Content_Portal/Documentation/SequentialDataStore/SDS_Views.md
Content_Portal/Documentation/SequentialDataStore/Units_of_Measure.md
Content_Portal/Documentation/http-status-codes.md

Putting Patch API after Update

Reordering SDS ACL API

---

Content_Portal/Documentation/SequentialDataStore/Reading_Data_API.md

Marking optional parameters as such following the API template guidelines

Restructure and improve Join Values content

---

Content_Portal/Documentation/Identity/Identity_AuthorizationCodeClient.md
Content_Portal/Documentation/Identity/Identity_ClientCredentialClient.md
Content_Portal/Documentation/Identity/Identity_HybridClient.md
Content_Portal/Documentation/Identity/Identity_Secret.md
Content_Portal/Documentation/Identity/Identity_User.md

Added link from relevant API topics to the new Authorization Best Practices concept topics

Digitaljoshua bestpractices links to concepts 2

---

Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Preview_Data_API.md
Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Resolved_Data_View_API.md
Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Resolved_Data_View_Preview_API.md
Content_Portal/Documentation/DataViews/DefineaDataView/Available_Field_Sets.md
Content_Portal/Documentation/DataViews/DefineaDataView/Field_Sets.md
Content_Portal/Documentation/DataViews/DefineaDataView/Grouping.md
Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md

Changing {FirstKey} to {Key} and {FirstStreamReferenceName} to {StreamReferenceName}.

Remove First in {FirstKey} {FirstStreamReferenceName}

---

Content_Portal/Documentation/Identity/Identity_and_Access_Management.md
Content_Portal/Documentation/OSIsoft_Cloud_Services.md
Content_Portal/Documentation/toc.yml
Content_Portal/OCS_Content_Portal_Overview.md

https://dev.azure.com/osieng/engineering/_sprints/taskboard/guild.Content%20Finn/engineering/2021/Q1/2021.03.03?workitem=195584

Updating the link to obtain the OCS account

---

Content_Portal/Documentation/Assets/asset-centric-data-api.md
Content_Portal/Documentation/Assets/asset-resolved-asset.md
Content_Portal/Documentation/Assets/asset-search-api.md
Content_Portal/Documentation/Assets/asset-status.md
Content_Portal/Documentation/Assets/assets.md

These changes are for updates in the Assets feature for Canvas GA.

Update from changes for Canvas GA

---

Content_Portal/Documentation/Operations/Operations_Metrics.md
Content_Portal/Documentation/SequentialDataStore/SdsStreamExtra.md
Content_Portal/Documentation/SequentialDataStore/Searching.md
Content_Portal/Documentation/SequentialDataStore/Units_of_Measure.md

https://dev.azure.com/osieng/engineering/_workitems/edit/194138

Glossary concepts work continuation

---

Content_Portal/Documentation/SequentialDataStore/Reading_Data_API.md
Content_Portal/Documentation/SequentialDataStore/SDS_Types.md
Content_Portal/Documentation/SequentialDataStore/Writing_Data_API.md
Content_Portal/Documentation/SequentialDataStore/indexes.md

Testing tabs for different languages (python, C# and javascript) in four topics (indexes, types, read/write data API) to be tested on zoomin. 
https://dev.azure.com/osieng/engineering/_workitems/edit/196564

Tabs in SDS 

---

Content_Portal/Documentation/SequentialDataStore/Filter_Expressions.md
Content_Portal/Documentation/SequentialDataStore/SDS_Types.md
Content_Portal/Documentation/SequentialDataStore/Units_of_Measure.md
Content_Portal/Documentation/SequentialDataStore/indexes.md

Removing SdsType and SdsTypeProperty from the table as they're internal types and should not be exposed to public

Removing SdsType and SdsTypeProperty

---

Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Preview_Data_API.md
Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Resolved_Data_View_API.md
Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Resolved_Data_View_Preview_API.md
Content_Portal/Documentation/DataViews/Data_Views_Overview.md
Content_Portal/Documentation/DataViews/DefineaDataView/Available_Field_Sets.md
Content_Portal/Documentation/DataViews/DefineaDataView/Consolidate_Data_Fields.md
Content_Portal/Documentation/DataViews/DefineaDataView/Data_Items_and_Groups.md
Content_Portal/Documentation/DataViews/DefineaDataView/Field_Mappings.md
Content_Portal/Documentation/DataViews/DefineaDataView/Field_Sets.md
Content_Portal/Documentation/DataViews/DefineaDataView/Queries.md
Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
Content_Portal/Documentation/DataViews/GetResolvedDataView/Resolved_Data_View.md
Content_Portal/Documentation/DataViews/Reference/Asset_Example.md
Content_Portal/Documentation/DataViews/Reference/Data_Views_Examples.md
Content_Portal/Documentation/DataViews/Reference/Example_Scenario.md
Content_Portal/Documentation/DataViews/Reference/toc.yml
Content_Portal/Documentation/DataViews/SecureDataViews/Securing_Data_Views.md
Content_Portal/Documentation/DataViews/toc.yml

Updated documentation for GA release of data views with assets, summaries and Uoms

Dataviews postcard GA release

---

Content_Portal/Documentation/Assets/asset-search-api.md

Please review the changes in asset-search-api.md
Thank you,
Laureen

Special characters in search strings

---

Content_Portal/Overview/what-does-ocs-do.md

Hi Laureen,
This is my assets piece for the What Does OCS Do section - - if you'd like to take a look at this and enter any comments, I'll just count your review as Doc QA.  I've incorporated comments from Victor Zhang and it's been through peer review.
Thanks,
Mark

Added Assets content to What Does OCS Do

---

Content_Portal/Documentation/Assets/assets.md
Content_Portal/Documentation/DataViews/DefineaDataView/Queries.md
Content_Portal/Documentation/SequentialDataStore/SDS_Types.md
Content_Portal/Documentation/SequentialDataStore/Units_of_Measure.md
Content_Portal/How_To_Guides/Assets/create-asset-from-type.md
Content_Portal/How_To_Guides/Assets/create-asset-type-asset-editor.md
Content_Portal/Overview/what-does-ocs-do.md

https://dev.azure.com/osieng/engineering/_sprints/taskboard/guild.Content%20Finn/engineering/2021/Q1/2021.03.24?workitem=200974

Updating links with warning in the build report in live OCS-docs

---

Content_Portal/add-organize-data/collect-data/connectors/omf/omf-overview.md

Hi Laureen - I drafted the text for the landing page, omf-overview.md
Thanks! /Joyce

Updated omf-overview

---

Content_Portal/Documentation/SequentialDataStore/Quick_Start.md

1. Reword the client identity section as suggested
2. Flip the orders so the authentication comes on top
3. Separate the error handling section from the QS steps

PBI 202848 - Calibrate the quick start section. 

---

Content_Portal/Documentation/SequentialDataStore/Reading_Data.md

Adding a section for data egress best practices

Best practices for reading data

---

Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md

About assets content for review

Ocs mrogers about assets subbranch

---

Content_Portal/Overview/get-started/clients/gs-client-authorization-clients.md
Content_Portal/Overview/get-started/clients/gs-client-credentials-clients.md
Content_Portal/Overview/get-started/clients/gs-hybrid-clients.md
Content_Portal/Overview/get-started/gs-namespaces.md
Content_Portal/set-up/authorization-code-client-procedure.md
Content_Portal/set-up/client-credentials-client-procedure.md
Content_Portal/set-up/hybrid-client-procedure.md
Content_Portal/set-up/namespaces-procedure.md
Content_Portal/set-up/roles-procedure.md
Content_Portal/set-up/users-procedure.md

fixing formatting errors in the get started topics

Adding formatting to UI elements in the set up topics

---

Content_Portal/Overview/what-does-ocs-do.md
Content_Portal/add-organize-data/configure-stream-views.md

1. Added uid to what does ocs do topic to link to it.
2. Created a task topic for configuring stream views.

Configure stream views

---

Content_Portal/Overview/get-started/gs-types.md
Content_Portal/add-organize-data/collect-data/connectors/omf/toc.yml
Content_Portal/set-up/set-up-overview.md

Doug,
You can ignore the edits to the other files. The file I need you to review is gs-types.md
Thanks,
Laureen

Updating Get started with types

---

Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md

Doc changes to OCS related to https://dev.azure.com/osieng/engineering/_workitems/edit/200785.

adding notes that both front slashes and back slashes are supported

---

Content_Portal/Documentation/Assets/asset-centric-data-api.md
Content_Portal/Documentation/Assets/asset-resolved-asset.md
Content_Portal/Documentation/Assets/asset-status.md
Content_Portal/Documentation/Assets/asset-type.md
Content_Portal/Documentation/Assets/assets-api.md
Content_Portal/Documentation/Assets/assets.md

Asset APIs should return SdsTypeCode as Strings

Modify SdsTypeCode to return a String

---

Content_Portal/Documentation/Assets/asset-centric-data-api.md
Content_Portal/Documentation/Assets/asset-status.md
Content_Portal/Documentation/Assets/assets-api.md
Content_Portal/Documentation/Assets/assets.md

added updates for:
- Additional behavior and rules updates for metadata and references name and id
- Removal of Name from Status

Update assets documentation

---

content/api-reference/sequential-data-store/sds-types.md

Please ignore the white space changes to the requests. I need to figure out why my text editor is adding that :stuck_out_tongue_winking_eye:

updating per Isaac's changes to wiki

---

content/add-organize-data/add-org-data-overview.md
content/add-organize-data/organize-data/data-context-overview.md

Hi Laureen
I updated data-context-overview.md and add-org-data-overview.md. Can you just read through the text and make sure it sounds ok? Now I know there are data views as well as stream views, I'm not certain they are mentioned correctly in the landing pages. 
Thanks! /Joyce

Updated data-context-overview.md and add-org-data-overview.md

---

content/external-references/sds-response-examples.yaml

Added test cases for types example responses

Sample test for SDS external reference links

---

content/api-reference/sequential-data-store/sds-types.md

This reverts commit e684a0446eb4b24be2dcb188c57c11816f611418.

Revert "adding Isaac's wiki edits to master"

---

content/api-reference/assets/asset-centric-data-api.md
content/api-reference/assets/asset-resolved-asset.md
content/api-reference/assets/asset-search-api.md
content/api-reference/assets/asset-status.md
content/api-reference/assets/asset-type.md
content/api-reference/assets/assets-acl-api.md
content/api-reference/assets/assets-api.md
content/api-reference/assets/assets.md

Reverts osisoft/OCS-Docs#495 Accidently merged into main

Revert "Updates to asset 04292021"

---

content/developer-guide/dev-guide-introduction.md

1. TOC title doesn't match the H1 title
2. The content may need work to provide more context.

Rendering the landing page for consistency

---

content/api-reference/community/toc.yml

Updating the toc title to match the manually generated API content

toc and topic title should match

---

content/external-references/responses.yaml

Creating response code for external reference in prep for work 
Added 201, and modified 200

Creating response code for external reference in prep for work 

---

content/api-reference/assets/assets-api.md
content/api-reference/community/toc.yml
content/api-reference/management/account-namespace.md
content/external-references/responses.yaml

Jokim pbi 220853 fix sd stenant

---

Content_Portal/Documentation/Management/Account_Namespace_1.md

fixed the erroneous terms for namespace API topic in master

fixed SDS tenant to tenant; fixed SDS type to type; in master branch

---

content/api-reference/management/account-namespace.md

Fixed SDS types to types; SDS tenant to tenant

---

Content_Portal/Documentation/Assets/access-control-api.md
Content_Portal/Documentation/Assets/asset-centric-data-api.md
Content_Portal/Documentation/Assets/asset-resolved-asset.md
Content_Portal/Documentation/Assets/asset-search-api.md
Content_Portal/Documentation/Assets/asset-status.md
Content_Portal/Documentation/Assets/asset-type.md
Content_Portal/Documentation/Assets/assets-api.md
Content_Portal/Documentation/Assets/assets.md

This PR is updating master with the changes made to main in PR #497.

Updating master with PR #497 updates

---

content/external-references/parameters.yaml

added (for specific instances with variations of value definitions) clientcredentialclientQuery, clientcredentialclientroleSkip, clientcredentialclientroleCount
edited values for clientcredentialclientId,  clientcredentialclientCount, clientcredentialclientSkip, query-user, skip-user, count-user

additions and edits to accommodate roles (tenant, clientcredentialsclient, user)

---

content/api-reference/assets/asset-search-api.md

Hi Anthony,
The HTML code showed up in green. I changed json --> html and that seems to have fixed it.
Thanks,
Laureen

Correcting syntax error

---

content/external-references/metadata-tags.yml

Added a new key (bulleted item for namespace) called namespace-identifier-requirements

Added a new key to metadata-tags.yml

---

content/external-references/common.yaml

added to forked branch:
-featurestateId
-blogId

added two new keys to common.yml

---

content/api-reference/omf-ingress/omf-ingress-access-control.md
content/api-reference/omf-ingress/omf-ingress-omf.md
content/api-reference/omf-ingress/omf-ingress-subscriptions.md
content/api-reference/omf-ingress/omf-ingress-topics.md

Docu pipe omf ingress

---

content/external-references/common.yaml

Added 4 new response codes for Anthony Tang & one new parameter for myself

---

index.md

updated landing page xref for dev guide

---

content/add-organize-data/store-data/streams/streams-procedure.md
content/add-organize-data/store-data/types/types-concept.md
content/add-organize-data/store-data/types/types-procedure.md
content/api-reference/community/community-shared-access.md
content/api-reference/data-views/define-a-data-view/quick-start-define-a-data-view.md
content/api-reference/rules/asset-rules/asset-rules.md
content/api-reference/sequential-data-store/sds-lp.md
content/api-reference/sequential-data-store/sds-quantities.md
content/api-reference/sequential-data-store/sds-stream-views.md
content/api-reference/sequential-data-store/sds-streams-metadata.md
content/api-reference/sequential-data-store/sds-streams-tags.md
content/api-reference/sequential-data-store/sds-streams.md
content/api-reference/sequential-data-store/sds-types.md
content/api-reference/sequential-data-store/sds-units-of-measure.md
content/developer-guide/sequential-data-store-dev/sds-lp-dev.md
content/developer-guide/sequential-data-store-dev/sds-quick-start.md
content/developer-guide/sequential-data-store-dev/sds-stream-views-dev.md
content/developer-guide/sequential-data-store-dev/sds-streams-dev.md
content/developer-guide/sequential-data-store-dev/sds-types-dev.md
content/developer-guide/sequential-data-store-dev/sds-uom.md

Merging development to main after updating links as a result of SDS reorg

Development to main

---

content/developer-guide/identity-dev/dev-guide-role-based-access-control.md

This change has been reviewed by development. 
Josh, I added you as a reviewer, but if you're not concerned you can approve and I'll merge into our Development branch. Thanks.

Dwicinas access control list enums

---

content/api-reference/tenant/tenant-root-access-control.md
content/api-reference/tenant/tenant-tenants.md

Revert "Merging DocuPipe-TenantMgmt to Development"

---

content/external-references/datacalls.yaml

The API in this section transforms data from the specified stream.

Removed lines and added to #stream-data-transform

---

content/external-references/backup-restore-authorization.yaml

for Sherlock to get around lack of support for controller files using authorization roles

added backup-restore-authorization.yaml

---

content/developer-guide/dev-guide-introduction.md

Hi, Anthony. Please review newly added 3rd paragraph on security best practices. After you have commented and approved, I will submit for final review and publishing. Please let me know if you have questions.
Thanks,
Vicki

Vtouati pbi 242473 security bp

---

content/developer-guide/sequential-data-store-dev/sds-search.md

This section also exists in the asset-search-api topic in the API reference.

adding Special Characters in Search Queries section into SDS Search topic

---

content/api-reference/assets/asset-search-api.md

Documentation update for PBI 246456: https://dev.azure.com/osieng/engineering/_sprints/taskboard/Azurite/engineering/2021/Q3/2021.08.18?workitem=246456

Pbi 246456 special characters in filter

---

content/communities/communities.md
content/communities/community-roles.md
content/communities/create-a-community.md
content/communities/delete-a-community.md
content/communities/manage-a-community.md
content/communities/manage-clients.md
content/communities/manage-users.md
content/communities/share-unshare-streams.md

Hey @dwicinas-osisoft , let's go over these when you return from vacation.

248763 communities doc qa

---

content/add-organize-data/collect-data/data-collection-overview.md

Revert "Vtouati pbi 219622 collect data"

---

content/developer-guide/identity-dev/dev-guide-role-based-access-control.md

Just one new description. It was missing for some reason.
got it from Neville (lead dev) in Soteria.
Please do a quick QA, Rainier...

added a description for AccessRights

---

content/api-reference/community/community-shared-access.md

This changes the document post Shared Access Service Retirement

Updating Shared Access Request Documentation

---

content/developer-guide/omf-dev/omf-ingress-specification.md

Replacement for https://github.com/osisoft/OCS-Docs/pull/334, which was really stale.

update for https://github.com/osisoft/OCS-Docs/pull/334

---

content/external-references/dataviews-response-examples.yaml
content/external-references/dataviews-summaries.yaml

Added an example and an entry in the data-views yaml

DocuPipe entries for get allfieldsets

---

content/api-reference/assets/assets.md
content/api-reference/assets/toc.yml

Needed to update this to reflect updated filenames

Update Assets TOC

---

content/add-organize-data/collect-data/connectors/pi-to-ocs/set-up-pi-to-ocs/config-utility.md

Vtouati pbi 271856 pda agent rule

---

content/add-organize-data/collect-data/connectors/pi-to-ocs/known-issues.md

Vtouati pbi 247089 server ids

---

content/api-reference/data-ingress/omf-ingress/toc.yml

* Alphabetized **API Reference > Data collection > OSIsoft Message Format**.
* Retitled "OMF access control" to "Access control".
[output preview](https://osisoft-dev.zoominsoftware.io/bundle/ocs-data-ingress-toc-update/page/api-reference/data-ingress/omf-ingress/omf-ingress-omf.html)

Data Collection TOC Reorg

---

content/api-reference/tenant/toc.yml

* Alphabetized **API Reference > Tenant Management**.
* Updated a couple topic names.

Tenant Management TOC Reorg

---

content/api-reference/data-views/toc.yml

* Alphabetized TOC for **API Reference > Data views**.
* The TOC in this branch was referencing what appear to be stale topics. I updated it to match the topics produced by docupipe, which is already published on production.

Data Views TOC Reorg

---

content/api-reference/community/toc.yml

* Alphabetized **API Reference > Communities**.
[Output preview](https://osisoft-dev.zoominsoftware.io/bundle/ocs-docupipe-community-toc-update/page/api-reference/community/community-overview.html)

Community TOC Reorg

---

content/api-reference/sequential-data-store/toc.yml

* Alphabetized **API Reference > Sequential Data Store**.
* Updated some titles.
[output preview](https://osisoft-dev.zoominsoftware.io/bundle/ocs-docupipe-sequential-data-store-toc-update/page/api-reference/sequential-data-store/sds-lp.html)

SDS TOC Reorg

---

content/api-reference/rules/asset-rules/toc.yml
content/api-reference/rules/metadata-rules/toc.yml
content/api-reference/rules/toc.yml

* Alphabetized the following TOCs:
* **API Reference > Rules**
* **API Reference > Rules > Asset rules**
* **API Reference > Rules > Metadata rules**
* Updated access control topic titles to "Access control"
[output preview](https://osisoft-dev.zoominsoftware.io/bundle/ocs-docupipe-rules-toc-update/page/api-reference/rules/rules-overview.html)

Rules TOC Reorg

---

content/add-organize-data/collect-data/connectors/omf/omf-connection-procedure.md
content/add-organize-data/store-data/streams/streams-concept.md
content/add-organize-data/store-data/streams/streams-procedure.md
content/add-organize-data/store-data/types/types-procedure.md
content/set-up/clients/authorization-code-client-procedure.md
content/set-up/clients/client-credentials-client-procedure.md
content/set-up/clients/hybrid-client-procedure.md
content/set-up/namespaces/namespaces-procedure.md
content/set-up/roles/roles-procedure.md
content/set-up/users/users-procedure.md

This is a start for the consistency edit of procedures.

Consistency edits

---

content/api-reference/assets/assets-resolved-asset.md

Removing OCS from resolved Asset

Remove OCS from resolved asset API documentation

---

content/add-organize-data/collect-data/connectors/pi-to-ocs/pi2ocs-rel-notes.md

Emergency hot fix for PI to OCS Agent required Release summary to be updated.

Update pi2ocs-rel-notes.md (#792)

---

content/add-organize-data/collect-data/connectors/pi-to-ocs/pi2ocs-rel-notes.md
content/add-organize-data/collect-data/connectors/pi-to-ocs/set-up-pi-to-ocs/config-utility.md

* adding tip about updating items per page to share a gang of streams
* fixing conflict
* Revert "fixing conflict"
This reverts commit 6a15cc2b8dd19b042ef0cf65849ef5d7e0b6fb95.
* Update pi2ocs-rel-notes.md (#792) (#793)
Emergency hot fix for PI to OCS Agent required Release summary to be updated.
* Vtouati pbi release summary criticalfix (#794)
* Update pi2ocs-rel-notes.md
Emergency hot fix for PI to OCS Agent required Release summary to be updated.
* Update pi2ocs-rel-notes.md
Edits
* Update config-utility.md
Remove ADH ref.
Co-authored-by: Mark Bishop <mbishop@osisoft.com>
Co-authored-by: Mark B <77757810+osisoft-mbishop@users.noreply.github.com>

Pbi 281196 remove ad href config utility (#798)

---

content/overview/get-started/clients/gs-client-authorization-clients.md
content/overview/get-started/clients/gs-client-credentials-clients.md
content/overview/get-started/clients/gs-hybrid-clients.md
content/overview/get-started/connections/gs-omf-connection.md
content/overview/get-started/connections/gs-pi-to-ocs-connection.md
content/overview/get-started/gs-asset-types.md
content/overview/get-started/gs-assets.md
content/overview/get-started/gs-getting-started-intro.md
content/overview/get-started/gs-namespaces.md
content/overview/get-started/gs-roles.md
content/overview/get-started/gs-stream-views.md
content/overview/get-started/gs-streams.md
content/overview/get-started/gs-types.md
content/overview/get-started/introduction-portal-interface.md

Aflores 274107 get started tasks

---

content/api-reference/tenant/tenant-features.md
content/api-reference/tenant/tenant-namespaces.md
content/api-reference/tenant/tenant-tenants.md

Removes unnessary branding from the Tenant Management API reference

Docu pipe tenant mgmt merge 1 6

---

content/overview/get-started/gs-asset-rules.md

correcting in-topic links

---

content/overview/get-started/gs-roles.md
content/overview/get-started/gs-types.md

Fixing some indent issues with notes that were causing note formatting issues and messed up step sequencing. This is a bug I found, not associated with any sprint work.
See problem here: https://osisoft-prod.zoominsoftware.io/bundle/ocs/page/overview/get-started/gs-types.html
Fix (branch output preview): https://osisoft-dev.zoominsoftware.io/bundle/ocs-indent-and-number-sequence-patch/page/overview/get-started/gs-types.html

fixing some indent issues

---

content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/transfer-data-to-ocs.md
content/api-reference/api-console.md
content/api-reference/regional-endpoints.md
content/api-reference/toc.yml
content/developer-guide/omf-dev/omf-editor.md
content/overview/get-started/view-profile.md
content/set-up/groups.md
content/set-up/identity-providers.md

Jason, the same edits apply to ADH.

Aflores 293563 peer review

---

content/external-references/common.yaml

-PiToDataHub routes has AgentID as required parameter , adding it

Add agentId

---

content/add-organize-data/collect-data/connectors/omf/omf-overview.md
content/add-organize-data/collect-data/connectors/pi-to-ocs/main-lp.md
content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-log-messages/download-tenant-log.md
content/add-organize-data/organize-data/metadata-rules/metadata-rules-concept.md
content/add-organize-data/store-data/store-data-overview.md
content/analytics.md
content/data-management.md
content/developer-tools.md
content/security.md

Hey Jason, here's my doc qa on your toc restructure. For the most part, I thought your changes looked really good. Most of my feedback is title updates for lower-level topics just so that they match the menus in OCS (and it seems like that work might have been out of scope here). Also a few style guide nitpicks.
All of the feedback I made here is granular. If you disagree with any of my feedback, you can check out the branch and revert the individual commit with `git revert <COMMIT#>`. I'll check in with you on Monday to make sure I'm making sense. 
Have a good weekend!

Pbi 287191 toc restructure update mb doc qa

---

content/communities/community-community-administration.md
content/communities/community-edit.md

@OutofmyOrbit, can you review my doc work for [290091](https://dev.azure.com/osieng/engineering/_workitems/edit/290091)? Doc edits were just as small as the code edits I imagine.

updating community edit topic for community name edits

---

content/add-organize-data/collect-data/connectors/omf/omf-connection-procedure.md
content/add-organize-data/collect-data/connectors/omf/omf-maintenance.md
content/add-organize-data/organize-data/data-views/data-view-maintenance.md
content/add-organize-data/organize-data/data-views/data-views.md
content/add-organize-data/organize-data/metadata-rules/metadata-rules-concept.md
content/add-organize-data/organize-data/metadata-rules/metadata-rules-maintenance.md
content/overview/get-started/resource-usage.md
content/set-up/clients/authorization-code-client-procedure.md
content/set-up/clients/client-credentials-client-procedure.md
content/set-up/clients/client-maintenance.md
content/set-up/clients/hybrid-client-procedure.md
content/set-up/users/user-maintenance.md
content/set-up/users/users-procedure.md

Hi Jason, I have some very minor suggestions for the info tabs content addons/changes in the pbi-246312-add-info-tabs branch from my peer view/doc QA. 
Note that this PR doesn't include the Roles maintenance topic since that file is in the pbi-246321-info-tabs branch. I will review in [PR 863]( https://github.com/osisoft/OCS-Docs/pull/863/files).

Pbi 308297 peer review doc qa add info tabs

---

content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/pi-point-change.md
content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/transfer-data-to-ocs.md
content/add-organize-data/collect-data/connectors/pi-to-ocs/set-up-pi-to-ocs/disable-ie-security.md
content/add-organize-data/collect-data/connectors/pi-to-ocs/set-up-pi-to-ocs/install-agent.md
content/add-organize-data/collect-data/connectors/pi-to-ocs/troubleshoot-pi-to-ocs/troubleshoot-failed-pi-mapping.md

a few minor fixes for the release today

minor release fixes

---

content/home/health.md

adding community bullets

---

content/communities/community-community-administration.md
content/communities/community-manage-preferred-region.md
content/communities/community-tenant-administration.md
content/toc.yml

Hi @pderks , I've completed a draft of the documentation to accompany [270116](https://dev.azure.com/osieng/engineering/_workitems/edit/270116). Can you please give it a technical review?
[doc preview](https://osisoft-dev.zoominsoftware.io/bundle/ocs-326872-use-preferred-region/page/communities/community-manage-preferred-region.html)

326872 use preferred region

---

content/external-references/common.yaml

add omfConnectionId to OMF section to support new OMF connection endpoints

add omfConnectionId to OMF section

---

content/visualize-data/power-bi-connector.md

"Interpolated Data Views" and "Stored Data Views" swapped

Small Update

---

content/communities/community-accept-invitation.md
content/communities/community-create-community.md

Also removing old stale images that will not be replaced.

adding field to provide contact email

---

content/communities/community-manage-shared-streams.md

@OutofmyOrbit, this PR is for doc work related to https://dev.azure.com/osieng/engineering/_workitems/edit/328912. It's a a short doc update to complement the new sharing process. 
I also removed a completely incorrect task unrelated to workitem that you can ignore during review.

338379-revised-approach-for-sharing-streams

---

content/external-references/communities-response-examples.yaml

Added error and reason phrase kv pairs

Update 207 response body example

---

content/add-organize-data/collect-data/software-mgmt/base-configurations.md
content/add-organize-data/collect-data/software-mgmt/configure-edge-system.md
content/add-organize-data/collect-data/software-mgmt/view-edge-system.md

Table added for switcher toggle.

Added table

---

content/developer-guide/excel-dev/use-excel.md

@jasnames, this PR addresses some style/grammar issues.

Minor grammar and style fixes for support writings

---

content/developer-guide/excel-dev/use-excel.md

@jasnames , this one is up to you, but I'd like to see more of a one-to-one relationship between the list and the headers.

suggesting new one-for-one wording

---

content/communities/community-community-administration.md
content/communities/community-edit.md

Hey Robert, I have a doc PR for community alias.

adding alias. Also adding tooltip for contact email

---

content/api-reference/content/content-overview.md
content/api-reference/content/tenant-service-blog.md
content/api-reference/content/toc.yml
content/api-reference/tenant/tenant-features.md
content/api-reference/tenant/tenant-namespaces.md
content/api-reference/tenant/tenant-root-access-control.md
content/api-reference/tenant/tenant-tenants.md
content/api-reference/tenant/toc.yml
content/api-reference/toc.yml

Merge latest from Infrastructure.

Docu pipe tenant mgmt

---

content/add-organize-data/organize-data/metadata-rules/metadata-rules-procedure.md

updating procedure to point at new search topic

---

content/api-reference/ocs-api-reference.md
content/developer-guide/data-views-dev/get-data-view-data/quick-start-get-data-view-data.md
content/developer-guide/sequential-data-store-dev/sds-read-data.md

added response format section to ocs-api-reference.md. removed specifics from other 2 docs, and added a link to details.

Response format

---

content/api-reference/ocs-api-reference.md

missed a reference to ADH in OCS documentation.

ADH reference fix

---

content/add-organize-data/organize-data/assets/remove-asset-types.md
content/add-organize-data/organize-data/assets/remove-assets.md
content/toc.yml

New topics for removing assets and asset types added. TOC updated.

Two New Topics

---

content/add-organize-data/collect-data/connectors/omf/omf-connection-procedure.md
content/add-organize-data/collect-data/connectors/omf/omf-overview.md
content/add-organize-data/store-data/types/types-best-practices.md
content/api-reference/api-console.md
content/api-reference/data-ingress/data-ingress.md
content/api-reference/data-ingress/omf-ingress/omf-ingress-omf.md
content/api-reference/data-ingress/toc.yml
content/api-reference/ocs-api-reference.md
content/developer-guide/omf-dev/omf-ingress-specification.md
content/developer-guide/omf-dev/omf-lp.md
content/developer-guide/toc.yml
content/overview/get-started/connections/gs-omf-connection.md
content/overview/get-started/gs-connections.md
content/overview/get-started/introduction-portal-interface.md
content/overview/what-does-ocs-do.md
content/overview/what-is-ocs.md

Changing OSIsoft Message Format to Open Message Format

Terminology Update

---

content/toc.yml

toc update

---

content/add-organize-data/store-data/streams/streams-add-event.md
content/toc.yml

Hey Robert, can I get a review for these docs related to [317220](https://dev.azure.com/osieng/engineering/_workitems/edit/317220)? There's really only one line related to your story.

adding new events topic to help

---

content/developer-guide/identity-dev/dev-guide-role-based-access-control.md

Made various fixes to the RBAC page.
-  Primarily to update Application Trustee as Client Trustee, and fix the associated examples.

RBAC page fixes

---

content/api-reference/assets/assets-asset-types.md
content/api-reference/assets/assets-assets-search.md
content/api-reference/assets/assets-assets.md
content/api-reference/assets/assets-resolved-asset.md

Docu pipe assets merge 050923

---

content/external-references/changebroker-summaries.yml

Including external summaries to reference within Streaming Updates / Change Broker API Documentation

Add changebroker-summaries.yml
